!#######################################################################
!
!     PURPOSE -
!
!        DEFINES variables used in command processing
!
!     CHANGE HISTORY -
!
!        $Log: commands_lg.h,v $
!        Revision 2.00  2007/11/03 00:49:10  spchu
!        Import to CVS
!
!PVCS
!PVCS       Rev 1.1   Wed Aug 04 10:23:26 1999   dcg
!PVCS     allow more definitions and longer commands
!PVCS
!PVCS       Rev 1.1   Mon Feb 22 16:05:36 1999   dcg
!PVCS    change in syntax for sun
!PVCS
!PVCS       Rev 1.0   Mon Feb 22 15:04:58 1999   dcg
!PVCS    Initial revision.
!
!#######################################################################
!
!  last_char is the location of the last character in cmd_stack
!  len_buff is the length of cmd_buffer
!  len_cmd is the length of a single command
!  maxlen_stack is the maximum stack length
!
integer last_char, len_buff, len_cmd, maxlen_stack,maxlen_buff, &
   maxcmd_args,maxnlevels
character*32 initname
parameter (maxlen_buff=16384)
parameter (maxnlevels=100)
parameter (maxcmd_args=16384)
common /ccommands_lg/ clevels, cmd_buff, cmd_temp, &
   command,cline,error_msg,initname
common /icommands_lg/ jlevels,nlevels,last_char, &
   len_buff, len_cmd, maxlen_stack
!
! nlevels is the number of recursion levels of command processing
! new levels are created by encountering 'infile' or 'input' commands
! or by the execution of 'dotasks'
! clevels(i) contains the name of the input file corresponding to
!  level i or 'interactive_lg' for interactive input or 'internal_lg'
!  for commands generated by a dotask
!
integer nlevels , jlevels(maxnlevels)
character*32 clevels(maxnlevels)
!
!  cmd_buffer is a the command buffer
!  cmd_temp is a scratch command work area
!  command is a holding area for a single command
!  cline is a holding area for one reading one line
!
character*80 cline
character*16384 cmd_buff, cmd_temp, command
character*132 error_msg
pointer (ipcmd_stack,cmd_stack)
character*1000 cmd_stack
!
!  definition_name is the list of names defined via the 'define' command
!  definition_off is the offset into definitions to find the
!    string that should replace the occurance of definition_name
!  maxdefinitions is the maximum number of definitions allowed
!  ndefinitions is the number of definitions
!  lastchar_def is the last character in 'defintion'
!
integer maxdefinitions,maxlen_def,ndefinitions,lastchar_def
parameter (maxdefinitions=1000)
integer definitions_off(1000)
character*32 definitions_name(1000)
common / idefines / ndefinitions,lastchar_def,definitions_off
common / cdefines / definitions_name
pointer (ipdefinition,definition)
character*1000 definition
